### PR TITLE
Connect to remote db

### PR DESCRIPTION
**Pull request by ciminibb**

### CODE REVIEW

**Comment by BlairBowen** [comment]
@ciminibb is there anything I can run for this PR so I can see it work?

**Comment by ciminibb** [comment]
@BlairBowen if you go to the feature branch in VS Code and run it in debug mode (choose Node) then you should see something like this
image

**Review by BlairBowen — APPROVED** [review]
Cool thanks I'll go ahead and merge this in

**Comment by BlairBowen** [comment]
@ciminibb actually just caught something. try running the moneyline file. I don't think I'm getting all the results.

**Comment by ciminibb** [comment]
@BlairBowen it's working on my end. I'm getting all 294 moneylines

**Comment by BlairBowen** [comment]
this is what I'm getting
image

**Comment by BlairBowen** [comment]
i guess the ... means its working probably just minimizing it

**Comment by ciminibb** [comment]
@BlairBowen oh I see what you're saying, I didn't catch that. But yeah I think that's what is happening. I just queries for only the rows in that lost range and it returned them

**Pull request merged**
